### ISSUE TITLE
MiniHud的地平仪消失了

### ISSUE THREAD

**Issue by SeclusionalAgar** [matrixsukhoi/voidmei#15]
1.542版本地平仪显示正常，1.547版本MiniHud地平仪消失了，无论对应值使用true或false
![da5cd2a936f5b6cab02c1b4888a1f5be](https://github.com/matrixsukhoi/voidmei/assets/128769489/397cf950-d4ca-4ae8-8892-230c0f021f37)

**Comment by matrixsukhoi** [comment]
1.55版已恢复
