### ISSUE TITLE
Scoop上未更新

### ISSUE THREAD

**Issue by tonyycdd** [matrixsukhoi/voidmei#18]
scoop还是ver. 1.547

**Comment by tu10ng** [comment]
![image](https://github.com/matrixsukhoi/voidmei/assets/47939948/542cac30-ef86-49af-b137-6b50737b11f1)

笑死我了,  最新版本的voidmei是1.55的, 上个版本是1.547, 但是55小于547, 所以scoop以为1.547是更新的版本

**Comment by tonyycdd** [comment]
> 用这个命令解决:
> 
> ```shell
> scoop update voidmei -f
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/47939948/305638516-542cac30-ef86-49af-b137-6b50737b11f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTcwMTUsIm5iZiI6MTcwODIxNjcxNSwicGF0aCI6Ii80NzkzOTk0OC8zMDU2Mzg1MTYtNTQyY2FjMzAtZWY4Ni00OWFmLWIxMzctNmI1MDczN2IxMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAwMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Y2FhN2NjMDE2MTk0NjhhYjc3NWMwOTYzMzUxZjVmNDE5NDRhOTMwYjA3MjFhM2M1YTBmOWFkNzgxMWRjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nryUIYchj0H2dezhD0t0zAML0-ZTJ1L7HnKToE1tBLg)
> 
> scoop上已经是最新版本了(voidmei 1.55). 但由于上个版本是1.547, 55小于547, 所以scoop以为1.547是更新的版本

ok, 非常感谢, 更新成功了. 
<论版本号命名的重要性>
