### ISSUE TITLE
scoop 更新 voidmei 无法通过hash校验

### ISSUE THREAD

**Issue by tonyycdd** [matrixsukhoi/voidmei#20]
1. 尝试了很多次, 每次错误信息都是一样的.

![image](https://github.com/matrixsukhoi/voidmei/assets/42673735/0419e6ab-0c12-41b9-ac19-98237f2a434b)

**Comment by tu10ng** [comment]
![image](https://github.com/matrixsukhoi/voidmei/assets/47939948/5e2d922d-55dd-4dbd-bc30-4a0e50e708da)
昨天下午4点半从release下载的sha256还是68aaf9, 今天早上7点半下载的就是69aa99了.
可以看到release的文件大小变了.
![image](https://github.com/matixsukhoi/voidmei/assets/47939948/7190757e-9f81-4a82-b049-72299a5424ef)

如果release的文件解压后能正常运行, 那么重新触发一下scoop bucket的自动更新, 同步下sha256的值就好了

**Comment by tonyycdd** [comment]
> ![image](https://private-user-images.githubusercontent.com/47939948/305754222-5e2d922d-55dd-4dbd-bc30-4a0e50e708da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE1ODcsIm5iZiI6MTcwODMxMTI4NywicGF0aCI6Ii80NzkzOTk0OC8zMDU3NTQyMjItNWUyZDkyMmQtNTVkZC00ZGJkLWJjMzAtNGEwZTUwZTcwOGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYWFjMWY5M2UzYTZkZWQxNDQ3MTdmZWUyZGY3MmViNTc0YTM1MWFlY2I2NzAxZTQ4NzRlODVlZDMwYzZlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ieb8LVoMZLFJNlKHvj-7r22WOsB4B9XcGqBeLi60Bhs) 昨天下午4点半从release下载的sha256还是68aaf9, 今天早上7点半下载的就是69aa99了.
> 
> 可以看到release的文件大小变了.
> 
> ![image](https://private-user-images.githubusercontent.com/47939948/305754508-c2617c10-fc61-4d2c-b4cf-e2c833336357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE1ODcsIm5iZiI6MTcwODMxMTI4NywicGF0aCI6Ii80NzkzOTk0OC8zMDU3NTQ1MDgtYzI2MTdjMTAtZmM2MS00ZDJjLWI0Y2YtZTJjODMzMzM2MzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNWI3M2JiMGQwY2M4YWZkNmU1NTcyYTM1OTZkODA5YjU4NGQ3Nzg0YTllZjAxY2I5MGZmYjc3ZTIzYjNlZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ysR8kMnkgXfrOtREyGfLorki4LkKV2OrkwIXkNB6n3c)
> 
> 如果release的文件解压后能正常运行, 那么重新触发一下scoop bucket的自动更新, 同步下sha256的值就好了

请问具体是怎么操作的, 不太会scoop.

**Comment by Lutra-Fs** [comment]
fixed in https://github.com/Lutra-Fs/scoop-bucket/commit/5f8811b6d8a2d247b408905217fca15edfb77eec. Thank you for your report

**Comment by tu10ng** [comment]
> 请问具体是怎么操作的, 不太会scoop.

在 https://github.com/Lutra-Fs/scoop-bucket 这里提 issue: https://github.com/Lutra-Fs/scoop-bucket/issues/1

我测试了下, scoop正确更新到了最新版本, 并成功运行:

``` shell
scoop update voidmei
```

**Comment by tonyycdd** [comment]
> > 请问具体是怎么操作的, 不太会scoop.
> 
> 在 https://github.com/Lutra-Fs/scoop-bucket 这里提 issue: [Lutra-Fs/scoop-bucket#1](https://github.com/Lutra-Fs/scoop-bucket/issues/1)
> 
> 我测试了下, scoop正确更新到了最新版本, 并成功运行:
> 
> ```shell
> scoop update voidmei
> ```

好的, 成功更新了, 谢谢
