### ISSUE TITLE
Voidmei.exe文件无法打开

### ISSUE THREAD

**Issue by LuoRomain** [matrixsukhoi/voidmei#21]
已经安装jre8，但双击击voidmei exe文件无反应。点击voidmei.jar可以正常打开，但在warthunder中无法正常使用。选择老版本尝试，发现149以下版本可以正常使用。

**Comment by tu10ng** [comment]
我这里可以正常运行. 

请你在战雷里试飞, 然后在voidmei的文件夹下, 打开一个终端窗口, 然后运行下面三个命令. : 

``` shell
# 确认下载下来的zip的完整性
certutil -hashfile '..\VoidMei_v1_560.zip' SHA256

java -version

java -jar .\VoidMei.jar
```
是否能看到如下输出? :

![image](https://github.com/matrixsukhoi/voidmei/assets/47939948/113e3f3e-3017-4581-b138-08356b09b720)

**Comment by LuoRomain** [comment]
![image](https://github.com/matrixsukhoi/voidmei/assets/160559712/cfd2839a-41be-48c6-8d16-9774167f1a83)
可以正常运行，就是voidmei.exe还是无法打开。那我以后就写一个bat打开voldmei吧。谢谢！

**Comment by LuoRomain** [comment]
发现这样运行的话如果要记录飞行数据，需要在本地目录创建record文件夹，否则整个程序都会错误。
![image](https://github.com/matrixsukhoi/voidmei/assets/160559712/b2f8a0fc-38a0-454d-a566-23ec023247dd)
