### ISSUE TITLE
界面不显示

### ISSUE THREAD

**Issue by Lawraence** [matrixsukhoi/voidmei#26]
与issue #9 问题相同，也是Win11，但是系统只有一个版本8更新411的java。
![java](https://github.com/matrixsukhoi/voidmei/assets/148807164/36ae16cf-ec14-479f-a58d-13572f082c7e)
还有就是解压完文件后文本名字出现了错误，如使用说明变成了"浣跨敤璇存槑.txt"，在运行程序的时候被Windows Defender SmartScreen告警（虽然问题不影响但是还是提一嘴）

**Comment by tonyycdd** [comment]
我也是这个版本, 但是运行正常的. 你试试看重装

**Comment by Lawraence** [comment]
谢谢，我刚刚又下载了，现在正常了
