### ISSUE TITLE
8111端口的地图分区与游戏中地图分区不同

### ISSUE THREAD

**Issue by tu10ng** [matrixsukhoi/voidmei#28]
处于G6区域时, 游戏中地图位置不是G6:

![X9CPDVA%4}(0) 21{7N~0HN](https://github.com/matrixsukhoi/voidmei/assets/47939948/950e2cd7-a39e-4067-bd3d-527865ef2c24)

处于G8区域时, 8111端口显示位于G8:

![KCN_CQTEQLGV2 $@RIT $AD](https://github.com/matrixsukhoi/voidmei/assets/47939948/5a5c1482-b4d3-413e-8304-523174c8723a)

可以看到两张图片中的地图分区不同

**Comment by matrixsukhoi** [comment]
已修复
