### ISSUE TITLE
miniHUD的网格坐标有偏差

### ISSUE THREAD

**Issue by LeePoposha** [matrixsukhoi/voidmei#33]
具体见附图，向左上方偏差了一格
![微信图片_20241106010706](https://github.com/user-attachments/assets/2b1104be-0e15-4c75-bbcf-80a5b0739f1c)

**Comment by LeePoposha** [comment]
以及，坐标左边、实时油量下面的那个图形，有点像半个准星，是做什么用的呢？能关掉吗？

**Comment by SeclusionalAgar** [comment]
那个是另一种意义上的油量指示，可以理解为在不受伤情况下，你现在飞机回转半径相比于0油增加的比例，一格是1/8

**Comment by matrixsukhoi** [comment]
坐标不准的问题应该已经修复了

**Comment by LeePoposha** [comment]
> 坐标不准的问题应该已经修复了

好的，确实修复了，非常感谢！
（小建议，如果在将来的改进中，能把程序快捷方式自动放进开始菜单栏就更好了，这样就不用每次更新都手动添加一遍）

**Comment by LeePoposha** [comment]
> 那个是另一种意义上的油量指示，可以理解为在不受伤情况下，你现在飞机回转半径相比于0油增加的比例，一格是1/8

理解了，感谢
