### ISSUE TITLE
[Package Manager] scoop support

### ISSUE THREAD

**Issue by Lutra-Fs** [matrixsukhoi/voidmei#6]
I've created a manifest for easy installation of voidmei via my scoop bucket. Just execute the command and it'll be installed with start menu access and updates. Don't hesitate to let me know if there are any issues with the content or the installation

```powershell
# install voidmei
scoop bucket add Lutra-Fs_scoop-bucket https://github.com/Lutra-Fs/scoop-bucket
scoop install Lutra-Fs_scoop-bucket/voidmei
# update voidmei
scoop update voidmei
```

**Comment by matrixsukhoi** [comment]
Thanks for the installation support.  Added in ReadMe.md.
